// (c) https://github.com/MontiCore/monticore

/* ============================================================ */
/* ========================= Plugins ========================== */
/* ============================================================ */

buildscript {
  dependencies {
    classpath "org.jline:jansi:$jansi_version"
  }
}

plugins {
  id 'java'

  id 'de.monticore.generator' version "$mc_version"
  id 'com.gradleup.shadow' version "$shadow_plugin_version"
  id "io.github.themrmilchmann.ecj" version "0.2.0"
  id 'jacoco'
  id 'com.adarshr.test-logger' version "$test_logger_verion"
  id 'maven-publish'
  id "com.github.sherter.google-java-format" version "0.9"    // Task "verifyGoogleJavaFormat" and "googleJavaFormat"
}

ecj {
  compilerVersion = "3.43.0"
}

/* ============================================================ */
/* ========================= Project ========================== */
/* ============================================================ */

group = 'de.monticore.lang'
layout.buildDirectory = layout.projectDirectory.dir("target")

/* ============================================================ */
/* ======================== Constants ========================= */
/* ============================================================ */

def grammarDir = layout.buildDirectory.dir("src/main/grammars")
def reportsDir = layout.buildDirectory.dir("generated-sources/monticore/sourcecode/reports")
def symbolsDir = layout.projectDirectory.dir("src/main/resources")

/* ============================================================ */
/* ======================= Configuration ====================== */
/* ============================================================ */

sourceSets {
  symbols {
    resources {
      srcDirs = [symbolsDir]
      include "**/*.sym"
    }
  }
  grammarsForVariant {
    resources {
      srcDirs = [grammarDir, reportsDir]
      include("**/*.mc4", "**/*.cd")
    }
  }
}

repositories {
  if(("true").equals(getProperty('useLocalRepo'))) {
    mavenLocal()
  }

  maven {
    credentials.username = mavenUser
    credentials.password = mavenPassword
    url = sePublicRepo
  }

  maven {
    credentials.username = mavenUser
    credentials.password = mavenPassword
    url = sePrivateRepo
  }

  mavenCentral()
}


configurations {
    grammar
    testSources {
      canBeConsumed = true
      canBeResolved = false
    }
}


googleJavaFormat {
  exclude '**/target/**'
}

verifyGoogleJavaFormat{
  ignoreFailures = true
  exclude "**"
}  // do not check format in "build"

tasks.register('checkfmt', com.github.sherter.googlejavaformatgradleplugin.VerifyGoogleJavaFormat) {
  dependsOn tasks.generateMCGrammars
}

tasks.register('fmt') {
  dependsOn tasks.named("googleJavaFormat")
}



test {
  useJUnitPlatform()
  finalizedBy jacocoTestReport
}

/* ============================================================ */
/* ======================= Dependencies ======================= */
/* ============================================================ */


dependencies {
  grammar "de.monticore:monticore-grammar:$mc_version"

  implementation "de.monticore:class2mc:$mc_version"
  implementation "de.se_rwth.commons:se-commons-logging:$se_commons_version"

  testImplementation ("de.monticore:monticore-grammar:$mc_version") {
      capabilities {requireCapability("de.monticore:monticore-grammar-tests") }
  }
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
  testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_jupiter_version"
  testImplementation "org.assertj:assertj-core:$assertj_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
}

/* ============================================================ */
/* ========================== Tasks =========================== */
/* ============================================================ */

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
  sourceCompatibility = JavaVersion.VERSION_21
  targetCompatibility = JavaVersion.VERSION_21
  options.encoding = 'UTF-8'
  options.headerOutputDirectory.convention(null)
  options.deprecation = false
  options.warnings = false
}

// build sources jar in addition
java {
  withJavadocJar()
  withSourcesJar()
  // Publish a feature-variant for compatibility - DEPRECATED
  registerFeature('grammars') {
    usingSourceSet(sourceSets.grammarsForVariant)
  }
}

sourcesJar.dependsOn project.collect { it.tasks.withType(MCGenTask)}

tasks.generateTestMCGrammars.dependsOn(tasks.grammarsForVariantJar)

// Ensure the grammars and GrammarsForVariant jars do not conflict
grammarsForVariantJar {
  archiveClassifier = "grammars-compat"
}

// Due to the report-CDs also being included, the following explicit dependency is required
tasks.processGrammarsForVariantResources.dependsOn(tasks.generateMCGrammars)

// generated java doc contains errors, disable for now
javadoc.failOnError = false


tasks.register('symbolJar', Jar) {
  from sourceSets.symbols.output
  includeEmptyDirs = false
  archiveBaseName = "ocl-library-symbols"
}

tasks.register('testSourcesJar', Jar) {
  from sourceSets.test.output + sourceSets.test.allSource + sourceSets.main.allSource
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  includeEmptyDirs = false
  archiveBaseName ="ocl-test-sources"
}

artifacts {
  testSources testSourcesJar
}

tasks.named("assemble") {
  dependsOn(symbolJar)
}

jar.dependsOn(symbolJar)
test.finalizedBy(testSourcesJar)

publishing {
  publications {
    mavenJava(MavenPublication) {
        from components.java
    }
  }
  repositories.maven {
    name = "$SE_Nexus_ID"
    credentials.username = mavenUser
    credentials.password = mavenPassword
    url = version.endsWith('SNAPSHOT') ? "$snapshotsRepoUrl" : "$releasesRepoUrl"
  }
}

