/**
 *
 * (c) https://github.com/MontiCore/monticore
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/**
 *
 * /* (c) https://github.com/MontiCore/monticore */
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/* (c) https://github.com/MontiCore/monticore */
package ocl.monticoreocl.ocl._ast;

import ocl.monticoreocl.oclexpressions._ast.ASTName2;
import ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary;

import java.util.Optional;

public class ASTOCLFile extends ASTOCLFileTOP {
  public ASTOCLFile() {
    super();
  }

  protected  ASTOCLFile (/* generated by template ast.ConstructorParametersDeclaration*/
      Optional<String> name
      ,
      Optional<ocl.monticoreocl.oclexpressions._ast.ASTName2> fileName
      ,
      java.util.List<ocl.monticoreocl.ocl._ast.ASTOCLConstraint> oCLConstraints

  ) {
    super(name, fileName, oCLConstraints);
  }

  public String getFileName() {
    return ASTOCLQualifiedPrimary.name2String(getFileName2());
  }
  public boolean isPresentFileName() {
    return isPresentFileName2();
  }

  public Optional<String> getFileNameOpt() {
    return ASTOCLQualifiedPrimary.name2StringOpt(getFileName2Opt());
  }
}
