/**
 *
 * (c) https://github.com/MontiCore/monticore
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/**
 *
 * /* (c) https://github.com/MontiCore/monticore */
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/* (c) https://github.com/MontiCore/monticore */
package ocl.monticoreocl.ocl._ast;

import de.monticore.types.types._ast.ASTType;

import java.util.Optional;

import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2String;

public class ASTOCLVariableDeclaration extends ASTOCLVariableDeclarationTOP {
  public ASTOCLVariableDeclaration() {
    super();
  }

  public  ASTOCLVariableDeclaration (/* generated by template ast.ConstructorParametersDeclaration*/
      Optional<ASTType> type
      ,
      ocl.monticoreocl.oclexpressions._ast.ASTName2 name
      ,
      de.monticore.expressionsbasis._ast.ASTExpression expression

  )
    /* generated by template ast.ConstructorAttributesSetter*/
  {
    super(type, name, expression);
  }

  public String getName() {
    return name2String(getName2());
  }
}
