/* (c) https://github.com/MontiCore/monticore */
package ocl.monticoreocl.ocl._ast;

import java.util.List;
import java.util.stream.Collectors;

import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2String;

public class ASTCompilationUnit extends ASTCompilationUnitTOP {

  public ASTCompilationUnit() {
    super();
  }

  public  ASTCompilationUnit (/* generated by template ast.ConstructorParametersDeclaration*/
      java.util.List<ocl.monticoreocl.oclexpressions._ast.ASTName2> packages
      ,
      java.util.List<de.monticore.types.types._ast.ASTImportStatement> importStatements
      ,
      ocl.monticoreocl.ocl._ast.ASTOCLFile oCLFile

  ) {
    super(packages, importStatements, oCLFile);
  }

  public List<String> getPackageList() {
    return getPackage2List().stream().map(s -> name2String(s)).collect(Collectors.toList());
  }
}
