package ocl.monticoreocl.ocl._ast;

import java.util.List;

import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2String;
import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2StringList;

public class ASTOCLThrowsClause extends ASTOCLThrowsClauseTOP {

  public ASTOCLThrowsClause() {
    super();
  }

  public  ASTOCLThrowsClause (/* generated by template ast.ConstructorParametersDeclaration*/
      java.util.List<ocl.monticoreocl.oclexpressions._ast.ASTName2> throwables2s

  ) { super(throwables2s); }

  public String getThrowables(int i) {
    return name2String(getThrowables2(i));
  }

  public List<String> getThrowablesList() {
    return name2StringList(getThrowables2List());
  }
}
