/**
 * ******************************************************************************
 *  MontiCAR Modeling Family, www.se-rwth.de
 *  Copyright (c) 2017, Software Engineering Group at RWTH Aachen,
 *  All rights reserved.
 *
 *  This project is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3.0 of the License, or (at your option) any later version.
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this project. If not, see <http://www.gnu.org/licenses/>.
 * *******************************************************************************
 */
package ocl.monticoreocl.ocl._ast;

import ocl.monticoreocl.oclexpressions._ast.ASTName2;

import java.util.Optional;

import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2String;
import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2StringOpt;

public class ASTOCLPostStatement extends ASTOCLPostStatementTOP {

  public ASTOCLPostStatement() {
    super();
  }


  protected  ASTOCLPostStatement (/* generated by template ast.ConstructorParametersDeclaration*/
      Optional<ASTName2> name2
      ,
      java.util.List<de.monticore.expressionsbasis._ast.ASTExpression> statementss

  ) {
    super(name2, statementss);
  }

  public Optional<String> getNameOpt() {
    return name2StringOpt(getName2Opt());
  }

  public String getName() {
    return name2String(getName2());
  }

  public boolean isPresentName() {
    return isPresentName2();
  }
}
