/* (c) https://github.com/MontiCore/monticore */
package ocl.monticoreocl.ocl._ast;

import ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary;

public class ASTOCLParameterDeclaration extends ASTOCLParameterDeclarationTOP {

  public ASTOCLParameterDeclaration() {
    super();
  }

  protected  ASTOCLParameterDeclaration (/* generated by template ast.ConstructorParametersDeclaration*/
      de.monticore.types.types._ast.ASTType type
      ,
      ocl.monticoreocl.oclexpressions._ast.ASTName2 name2

  ) {
    super(type, name2);
  }

  public String getName() {
    return ASTOCLQualifiedPrimary.name2String(getName2());
  }
}
