/**
 * ******************************************************************************
 *  MontiCAR Modeling Family, www.se-rwth.de
 *  Copyright (c) 2017, Software Engineering Group at RWTH Aachen,
 *  All rights reserved.
 *
 *  This project is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3.0 of the License, or (at your option) any later version.
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this project. If not, see <http://www.gnu.org/licenses/>.
 * *******************************************************************************
 */
package ocl.monticoreocl.ocl._ast;

import ocl.monticoreocl.oclexpressions._ast.ASTName2;
import ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary;

import java.util.Optional;

public class ASTOCLFile extends ASTOCLFileTOP {
  public ASTOCLFile() {
    super();
  }

  protected  ASTOCLFile (/* generated by template ast.ConstructorParametersDeclaration*/
      Optional<String> name
      ,
      Optional<ocl.monticoreocl.oclexpressions._ast.ASTName2> fileName
      ,
      java.util.List<ocl.monticoreocl.ocl._ast.ASTOCLConstraint> oCLConstraints

  ) {
    super(name, fileName, oCLConstraints);
  }

  public String getFileName() {
    return ASTOCLQualifiedPrimary.name2String(getFileName2());
  }
  public boolean isPresentFileName() {
    return isPresentFileName2();
  }

  public Optional<String> getFileNameOpt() {
    return ASTOCLQualifiedPrimary.name2StringOpt(getFileName2Opt());
  }
}
