package ocl.monticoreocl.ocl._ast;

import ocl.monticoreocl.oclexpressions._ast.ASTName2;

import java.util.Optional;

import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2String;
import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2StringOpt;

public class ASTOCLPostStatement extends ASTOCLPostStatementTOP {

  public ASTOCLPostStatement() {
    super();
  }


  protected  ASTOCLPostStatement (/* generated by template ast.ConstructorParametersDeclaration*/
      Optional<ASTName2> name2
      ,
      java.util.List<de.monticore.expressionsbasis._ast.ASTExpression> statementss

  ) {
    super(name2, statementss);
  }

  public Optional<String> getNameOpt() {
    return name2StringOpt(getName2Opt());
  }

  public String getName() {
    return name2String(getName2());
  }

  public boolean isPresentName() {
    return isPresentName2();
  }
}
