package ocl.monticoreocl.ocl._ast;

import java.util.List;

import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2String;
import static ocl.monticoreocl.oclexpressions._ast.ASTOCLQualifiedPrimary.name2StringList;

public class ASTQualifiedName extends ASTQualifiedNameTOP {

  public ASTQualifiedName() {
    super();
  }

  public ASTQualifiedName (/* generated by template ast.ConstructorParametersDeclaration*/
      java.util.List<ocl.monticoreocl.oclexpressions._ast.ASTName2> part2s
  ) { super(part2s); }

  public List<String> getNameList() {
    return name2StringList(getPart2List());
  }
  public String getPart(int i) { return name2String(getPart2(i)); }
}
