/* generated by template symboltable.ModelNameCalculator*/




package ocl.monticoreocl.ocl._symboltable;

import de.monticore.symboltable.SymbolKind;

import java.util.LinkedHashSet;
import java.util.Set;

public class OCLModelNameCalculatorTOP extends de.monticore.CommonModelNameCalculator {

  @Override
  public Set<String> calculateModelNames(final String name, final SymbolKind kind) {
    final Set<String> calculatedModelNames = new LinkedHashSet<>();

      if (OCLFileSymbol.KIND.isKindOf(kind)) {
        calculatedModelNames.addAll(calculateModelNamesForOCLFile(name));
      }

    return calculatedModelNames;
  }

  protected Set<String> calculateModelNamesForOCLFile(String name) {
    final Set<String> modelNames = new LinkedHashSet<>();
    modelNames.add(name);
    return modelNames;
  }


}
